name: user-mgmt

services:
  user-mgmt-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-mgmt-service
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_PASSWORD: ${DB_PASSWORD:-letmein}
      JWT_SECRET: ${JWT_SECRET:-R8HNg7CEupCmYvSyXVqGxpVhaa0NIsIX5yLVxTyfAVhNjniLX44}
      LOG_LEVEL: ${LOG_LEVEL}
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    container_name: user-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-app_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-letmein}
      POSTGRES_DB: ${POSTGRES_DB:-user-db}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql
volumes:
  postgres-data:
