CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(50) DEFAULT 'ROLE_USER',
    deleted BOOLEAN DEFAULT FALSE
);

INSERT INTO users (
    first_name, last_name, email, role, password_hash
  ) VALUES (
    'Admin', 'User', 'admin@example.com', 'ROLE_ADMIN',
    -- bcrypt hash of 'admin123'
    '$2a$12$fCDqmhZ7AzdSRXOlwy83k.eggjpW3mVhcnEpw8NGooYPni7YgsLJe'
  ) ON CONFLICT (email) DO NOTHING;
